### ISSUE TITLE
r chunks -- make it cleaner

### ISSUE THREAD

**Issue by KimboGilda** [zimmewen/cma_week3#1]
First of all, there is no need to include the following lines -- demo -- to your solution
https://github.com/zimmewen/cma_week3/blob/b23137ed9e896fe549ed80767a57599ae4ba6491/week3_exercise.Rmd#L22-L88

**This is just a recommendation**: Since you are wishing to create an html output, it would be better to customise some of the `r chunks` settings, so you can have a cleaner output.
https://github.com/zimmewen/cma_week3/blob/b23137ed9e896fe549ed80767a57599ae4ba6491/week3_exercise.Rmd#L15-L19

You can set the r chunk to ` {r message=FALSE, warning=FALSE}`  

that way you will not receive all the unnecessary messages and warnings, every time you are knitting an .Rmd document.

**Comment by zimmewen** [comment]
Done together with issue #1.
