### ISSUE TITLE
define threshold for static points

### ISSUE THREAD

**Issue by KimboGilda** [zimmewen/cma_week3#2]
as a threshold for defining whether a point is static or not you did the following
https://github.com/zimmewen/cma_week3/blob/b23137ed9e896fe549ed80767a57599ae4ba6491/week3_exercise.Rmd#L128-L132

instead you should again derive the mean of the `stepMean` variable you created previously
```caro60 <- caro60 %>%
  mutate(
    static = stepmean < mean(stepmean, na.rm = TRUE)
  )
```

**Comment by zimmewen** [comment]
Corrected that step and uploaded new file.
